name: notes
services:
  api:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    ports:
      - "8000"
    volumes:
      - ./keys.env:/app/keys.env
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "80:80"